name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  clean:
    description: 'Whether to execute `git clean -ffdx -e Library && git reset --hard HEAD` before fetching'
    default: true
  lfs:
    description: 'Whether to download Git-LFS files'
    default: false
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    default: 0    

runs:
  using: 'composite'
  steps:

    - name: Reset Working Copy
      if: ${{ inputs.clean == 'false' }} 
      shell: bash
      run: |
        # prevent fatal errors on fresh runners        
        git clean -ffdx -e Library || true
        git reset --hard HEAD || true
        
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ github.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.lfs }}
        ref: ${{ inputs.ref }}
        clean: ${{ inputs.clean }}
        filter: ''

    - name: Check for unresolved Git LFS pointer files
      shell: bash
      run: |
        echo "Checking for Git LFS pointer files..."

        if git grep -I "version https://git-lfs.github.com/spec/v1" -- .; then
          echo ""
          echo "ERROR: Found Git LFS pointer files instead of real files."
          echo "This usually means Git LFS failed to download the actual content."
          exit 1
        fi
        echo "OK: No Git LFS pointer files found."        
        
    - name: Git Status
      shell: bash
      run: |
        git status
