name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  clean:
    description: 'Whether to execute `git clean -ffdx -e Library && git reset --hard HEAD` before fetching'
    default: true
  lfs:
    description: 'Whether to download Git-LFS files'
    default: false

runs:
  using: 'composite'
  steps:
        
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ github.token }}
        fetch-depth: 0
        lfs: ${{ inputs.lfs }}
        ref: ${{ inputs.ref }}
        clean: ${{ inputs.clean }}
        filter: ''

    - name: Show last git logs
      if: failure()
      shell: bash
      run: |
        git lfs logs last || true

    - name: Reset Working Copy
      if: ${{ inputs.clean }} == 'false'
      shell: bash
      run: |
        git clean -ffdx -e Library && git reset --hard HEAD
        
    - name: Git Status
      shell: bash
      run: |
        git status























