name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
inputs:
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  clean:
    description: 'Whether to execute `git clean -ffdx -e Library && git reset --hard HEAD` before fetching'
    default: true
  lfs:
    description: 'Whether to download Git-LFS files'
    default: false
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    default: 0    

runs:
  using: 'composite'
  steps:

    - name: Reset Working Copy
      if: ${{ inputs.clean == 'false' }} 
      shell: bash
      run: |
        # prevent fatal errors on fresh runners
        git clean -ffdx -e Library || true
        git rm --cached -r . || true
        git reset --hard HEAD || true
        
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ github.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        lfs: ${{ inputs.lfs }}
        ref: ${{ inputs.ref }}
        clean: ${{ inputs.clean }}
        filter: ''

    - name: Show last git logs
      if: failure()
      shell: bash
      run: |
        git lfs logs last || true
        
    - name: Git Status
      shell: bash
      run: |
        git status
